[package]
name = "client"
version = "0.1.0"
authors = ["dougfort <doug.fort@gmail.com>"]
edition = "2018"

[dependencies]
failure = "0.1"
hex = "0.3"
sha2 = "0.8"
cards = {path = "../cards" }
game = {path = "../game" }
