[package]
name = "client"
version = "0.1.0"
authors = ["dougfort <doug.fort@gmail.com>"]
edition = "2018"

[dependencies]
failure = "0.1.5"
hex = "0.3.2"
cards = {path = "../cards" }
game = {path = "../game" }
