[package]
name = "player"
version = "0.1.0"
authors = ["dougfort <doug.fort@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
hex = "0.3.2"
rustyline = "8.2"
cards = {path = "../cards" }
client = {path = "../client" }
